mono/mono-addins

configure.ac

Avoids a build failure when cross-compiling.

Use PKG_PROG_PKG_CONFIG macro

---

configure.ac

With this, user will know that he can build without the GUI features
if she wants.

configure: if gtk is not found, advice about --disable-gui

---

configure.ac

gmcs is no more in modern Mono

[configure] gmcs -> mcs

---

Mono.Addins.GuiGtk3/Mono.Addins.GuiGtk3.csproj

The new addins icons introduced in b9fa673 have duplicate names.  Fix by
following the same schemas used for Mono.Addins.Gui and adding some '@2x'
where they are missing.

Fix Mono.Addins.GuiGtk3 build.

---

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj
Mono.Addins.Gui/Mono.Addins.Gui.csproj
Mono.Addins.MSBuild/Mono.Addins.MSBuild.csproj
Mono.Addins.Setup/Mono.Addins.Setup.csproj
Mono.Addins/Mono.Addins.csproj
mautil/mautil.csproj

If anyone tried to build mono-addins with the xbuild 12.0 engine [1]
that comes with mono 4.2.1 [2] \(quite widespread given that it's the
version bundled with Ubuntu 16.04.x LTS), the build would not
work [3].
[1]
```
$ xbuild --version
XBuild Engine Version 12.0
Mono, Version 4.2.1.0
Copyright (C) 2005-2013 Various Mono authors
```
[2] 
```
$ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
TLS:           __thread
SIGSEGV:       altstack
Notifications: epoll
Architecture:  amd64
Disabled:      none
Misc:          softdebug
LLVM:          supported, not enabled.
GC:            sgen
```
[3]
```
$ ./autogen.sh
I am going to run ./configure with no arguments - if you wish …
```

build: fix build with xbuild 12.0 engine (mono 4.2.1)

---

configure.ac

configure.ac is not autogenerated, the autogenerated one is
the `configure` file that gets generated after running autoconf.
(If this was autogenerated, it would probably not be present
in the repository.)

configure.ac: remove wrong comment

---

.gitignore
Mono.Addins.Setup.nuspec
Mono.Addins.Setup/Mono.Addins.Setup/SetupService.cs
Mono.Addins.nuspec

Allows producing mpacks that can be consumed by older versions of MD/XS on Mac/Windows, current MD on Linux,  and Cydin.

Fix zip back-compat

---

Mono.Addins/Mono.Addins.Database/FileDatabase.cs

On Linux filesystems, the maximum filename length is 255 bytes. However, when using home directory encryption (as opposed to full-disk encryption), user-visible filenames are backed by encrypted filenames which are much longer. As a result, filenames longer than about 143 characters cannot be stored on encrypted systems.
A limit of 130 gives room for a fairly lengthy file extension.
This limit, unlike MAX_PATH on Windows, is per-file not for the full path name.

Cap length of FileDatabase filenames at 130.

---

Mono.Addins.Setup/Mono.Addins.Setup/AddinPackage.cs
Mono.Addins.Setup/Mono.Addins.Setup/SetupService.cs

ICSharpCode.ZipFile needs to be closed so ZipEntries get cleaned up, so does CloseEntry have to be called after writing a ZipEntry.

[Perf] Plug possible leaks.

---

Mono.Addins/Mono.Addins.Database/Util.cs

The downside of the previous method is that it was throwing a first-chance exception on native binaries. This makes it harder to debug.
Also the new implementation is 4 times faster for success cases and 5-6 times faster for failure cases (native binary).

Add an IsManagedAssembly() implementation that doesn't throw for native assemblies

---

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector/Reflector.cs
Mono.Addins/Mono.Addins.Database/AddinScanner.cs

Making this item a lazy will make condition attributes only queried when they have to be. Empirical testing shows 1 second time spent (from 2s down to 1s) on 39 assembly files by halving the number of calls.

[Perf] Optimize assembly scanning by not doing unnecessary work

---

Mono.Addins/Mono.Addins.Database/AddinScanner.cs
Mono.Addins/Mono.Addins.csproj
Mono.Addins/Mono.Addins/AddinLocalizerAttribute.cs

An addin can now replace the localizer used when translating strings
by specifying the type with the AddinLocalizer attribute.
[assembly:AddinLocalizer("MyNamespace.MyAddinLocalizer")]

Allow custom addin localizer to be defined with attribute

---

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector/Reflector.cs
Mono.Addins/Mono.Addins.Database/AddinScanner.cs
Mono.Addins/Mono.Addins.Database/DefaultAssemblyReflector.cs
Mono.Addins/Mono.Addins.Database/IAssemblyReflector.cs

The reflector now takes into account that some assemblies only have to
be loaded if they reference Mono.Addins. For example, when looking for
a subclass of Mono.Addins.ExtensionNode, only assemblies that have a
Mono.Addins reference can define such class.
This optimization can be applied in several cases and reduces the
number of assemblies that are loaded.
An UnloadAssembly method has also been added, and it is used to unload
potential add-in assemblies when there is an error while scanning.

Optimize the cecil reflector

---

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj
Mono.Addins.Setup/Mono.Addins.Setup.csproj
Mono.Addins/Mono.Addins.csproj
Mono.Addins/packages.config

The VSMac 2017-08 branch build breaks with mono 5.6.0.x:
Using "ReportAssetsLogMessages" task from assembly "/usr/local/share/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/build/../tools/net46/Microsoft.NET.Build.Tasks.dll".
Task "ReportAssetsLogMessages"
/usr/local/share/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(323,5): error MSB4018: The "ReportAssetsLogMessages" task failed unexpectedly. [/Users/ludovic/Xamarin/monodevelop/main/external/RefactoringEssentials/RefactoringEssentials.2017/RefactoringEssentials.csproj]
/usr/local/share/dotnet/sdk/2.0.0/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(323,5): error MSB4018: System.TypeLoadException: Could not resolve type with token 0100005b (from typeref, class/assembly …

Fix bxc #58815 build breakage

---

Mono.Addins.Setup/Mono.Addins.Setup/SetupTool.cs

This mirrors the behavior of the commandline `check-install` option with `AddinEngine.CheckInstalled` method that does a similar processing.

Ensure that the given addin is enabled when checking for its installation.

---

Mono.Addins.Setup/Mono.Addins.Setup/SetupService.cs

Without this fix, the .zip archive created is still using backslashes on Windows.

Use DirectorySeparatorChar '\\' instead of PathSeparator ';'

---

Mono.Addins/Mono.Addins.Database/FileDatabase.cs

The format of the addin cache data is something like below:
Users_therzok_Work_md_monodevelop_main_build_AddIns_MonoDevelop.AzureFunctions_azure-functions-cli-66a932fb_nb_abf27ece.data
That means that the code which is removed was looking for something that would match:
<Full_Path>_sha*.data
Only 1 item matches that (the direct query), and if the direct query did not match, it means scanning
the whole folder for another file which matches the pattern is useless.
Reduces AddinDatabase.Update for full VSMac from 1.95s to 0.72s, that's 1.23 spent
just doing IO via Directory.GetFiles.

[FileDatabase] Optimize addin scanning

---

Mono.Addins/Mono.Addins.Database/AddinDatabase.cs
Mono.Addins/Mono.Addins/ExtensionContext.cs

Every time we load an extension point, we sort the data by the addin
dependency tree.
In the case of 100 extensions, we end up doing a linear search with
every addin when inserting into the sorted list.
The old code's limitation was that we had to create an addin dependency
tree on the spot for every addin with every addin.
That means we'd traverse the whole tree and construct it on every iteration,
for every check.
That potentially rounds up to O(N_DEPS) * O(N_EXTENSIONS^2).
This code makes the tree construction on demand, so the checking where it fits
is an O(1) for constructed cache, and O(N_DEPS) for non-constructed.
We transitively propagate deps of an addin to the parent, for hitting O(1)
in all cases.
The reason we now put the Name instead of FullId when doing recursive search is …

[Database] Cache the dependency tree in AddinDependsOn

---

Mono.Addins/Mono.Addins.Database/AddinDatabase.cs
Test/UnitTests/TestScan.cs
Test/UnitTests/UnitTests.csproj
Test/UnitTests/Util.cs
Test/test-files/ScanTest/Addins/SimpleAddin.addin.xml
Test/test-files/ScanTest/App/SimpleAddin.addin.xml
Test/test-files/ScanTest/App/SimpleApp.addin.xml

If the same addin with same version exists in the app folder and in the user's addins folder, always load the one in the user's folder. This will make it easier to test add-ins running on apps that bundle
the same version of the add-in.

 Tweak add-in loading logic

---

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj

Uncovered by https://github.com/mono/monodevelop/issues/4237
```
"/home/pi/sources/monodevelop/main/Main.sln" (default target) (1) ->
"/home/pi/sources/monodevelop/main/src/core/MonoDevelop.Startup/MonoDevelop.Startup.csproj" (default target) (13) ->
"/home/pi/sources/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj" (default target) (14:2) ->
Mono.Addins.CecilReflector/Reflector.cs(373,3): error CS0012: The type `System.Collections.Generic.ISet`1<T>' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' [/home/pi/sources/monodevelop/main/external/mono-addins/Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj]
```

Fix possible build error in CecilReflector

---

Mono.Addins/Mono.Addins.Database/AddinFileSystemExtension.cs
Mono.Addins/Mono.Addins/Addin.cs
Mono.Addins/Mono.Addins/AddinEngine.cs
Mono.Addins/Mono.Addins/AddinManager.cs
Test/UnitTests/ExtensionModel/GlobalInfoConditionAttribute.cs
Test/UnitTests/TestScanDataFileGeneration.cs
Test/test-files/ScanDataFilesTest/Addins/SimpleAddin2.addin.xml
Test/test-files/ScanDataFilesTest/App/SimpleApp.addin.xml

When using pre-generated add-in scan files, sometimes
updating the add-in db may cause a crash. That's because
a post-update process tries to refresh the domain of each add-in
and it is done by getting the domain of the folder that contains
the add-in. When using scan data files, there is only folder info
for the root directory, not for each add-in directory, so the domain
query fails.
The solution is to not try to refresh the domain. A domain change of
an add-in at run-time is an unlikely scenario that in general is not
properly supported, and it requires a restart.

Fix crash when re-scanning add-in folders

---

Mono.Addins/Mono.Addins/ExtensionNode.cs

When translating strings defined in an addin.xml file the addin
and its dependencies will be loaded. If conditions or extension
objects used this will result in addin assemblies being loaded.
If the addin does not have a localizer then the AddinEngine's
default localizer will be used and the addin does not need to
be loaded just to translate the string.

Avoid loading the addin if it has no localizer

---

Mono.Addins.Setup/Mono.Addins.Setup.csproj
Mono.Addins.Setup/Mono.Addins.Setup/AddinStore.cs
Mono.Addins.Setup/Mono.Addins.Setup/DownloadFileRequest.cs
Mono.Addins.Setup/Mono.Addins.Setup/HttpClientProvider.cs
Mono.Addins.Setup/Mono.Addins.Setup/Repository.cs
Mono.Addins.Setup/Mono.Addins.Setup/WebRequestHelper.cs

By default the HttpClient will be used when downloading files such
as the addin repository xml and any custom images for the addin
manager dialog. Also a custom HttpClient factory can be supplied
instead of the default HttpClient creation. The WebRequestHelper
is still supported if a custom web request handler is being used
instead.

Support using HttpClient when downloading files

---

Mono.Addins.Setup/Mono.Addins.Setup/AddinStore.cs

Use Task.Wait instead to avoid CPU use.

Remove SpinWait

---

Mono.Addins/Mono.Addins.Database/AddinDatabase.cs
Mono.Addins/Mono.Addins.Database/DatabaseConfiguration.cs
Mono.Addins/Mono.Addins/AddinRegistry.cs

When initializing an add-in dabatase ensure that all add-ins have all
their dependencies enabled. The database takes care to keep the
enabled status consistent at run-time (so if an add-in is disabled,
all dependent add-ins will also be disabled). However, that status
may already be inconsistent when loading the database, and that
may cause add-in loading issues. This may happen for example if
add-in A is disabled, and then an add-in B that depends on A is
installed externally, outside of the control of the db. With the
changes of this commit, when the db is initialized it will detect
that B depends on a disabled add-in and it will be disabled too.
Fixes VSTS #952473

Fix add-in status consistency issue

---

Mono.Addins.Gui/Mono.Addins.Gui/AddinManagerWindow.cs
Mono.Addins.Gui/Mono.Addins.Gui/ProgressDialog.cs
Mono.Addins.Gui/Mono.Addins.Gui/Services.cs

Fixes VSTS #935546 - [Shell] Extensions screen is not well aligned to parent
This PR completes mono/monodevelop#8782

Fixes current window allocation in Extension dialog and all the children windows 

---

Mono.Addins/Mono.Addins.Database/AddinScanner.cs

When Mono.Addin is loading addins it is resolving dependencies internally and overriding the AppDomain.AssemblyResolve
This makes it possible to add additional search paths for the dependency check.
MONO_ADDIN_ADDITIONAL_PATH = "C:\Program Files\Framework\bin"
Will make the Addin loader look for Assemblies in "C:\Program Files\Framework\bin" first and if a match is found use that.
It will fallback to the normal internal check if no match found.

Additional search paths for internal AssemblyResolve.

---

Mono.Addins.Setup/Mono.Addins.Setup/SetupTool.cs

* Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1160536
---
This is how it prints out
```
Microsoft.VisualStudio.Mac.RazorAddin,8.0.20200520.11 [Disabled] Razor Language Services (/Users/masinha/code/vsmac/external-addins/razor/build/Razor-20200520.11-b518ea23-master.mpack/Microsoft.VisualStudio.Mac.RazorAddin.dll)
Xamarin.AzureSupport,8.8 [Enabled] Azure Support (/Users/masinha/code/vsmac/main/build/AddIns/Xamarin.AzureSupport/Xamarin.AzureSupport.dll)
MonoDevelop.AspNetCore,8.8 [Enabled] ASP.NET Core Support (/Users/masinha/code/vsmac/main/build/AddIns/AspNetCore/MonoDevelop.AspNetCore.dll)
MonoDevelop.MonoAndroid,8.6 [Enabled] Android development (/Users/masinha/code/vsmac/external-addins/xamarin-extensions/build/MonoDevelop.MonoDroid/MonoDevelop.MonoDroid.dll) …
```

Fix #1160536 and list the complete addin id when using list method

---

Mono.Addins/Mono.Addins.Database/AddinFileSystemExtension.cs
Version.props

Loading of CecilReflector was failing in .NET core since it was
being loaded in the LoadFrom context.

Fix CecilReflector load issue

---

Mono.Addins.Setup/Mono.Addins.Setup/AddinPackage.cs
Mono.Addins.Setup/Mono.Addins.Setup/SetupService.cs

This API is needed to query mpack information during addin install in the Extensions Window.

Surface ReadAddinHeader info from SetupService

---

Mono.Addins/Mono.Addins.Database/AddinRegistryUpdater.cs
Mono.Addins/Mono.Addins.Database/AddinScanFolderInfo.cs
Mono.Addins/Mono.Addins.Database/AddinScanResult.cs
Mono.Addins/Mono.Addins.Database/AddinScanner.cs
Mono.Addins/Mono.Addins.Description/ModuleDescription.cs
Test/UnitTests/TestScanDataFileGeneration.cs

In some cases when add-ins are downgraded the add-in database may be left in an invalid status. This happened because the add-in scanner did not properly compare the versions of the old and the new add-in, so it did not uninstall the old add-in when versions were different. This resulted on the old and new descriptions of the add-in to be kept in the database, and it might generate add-in dependency errors.
This also happened when upgrading, but since the engine always loads add-ins with the highest version it doesn't matter if there is one with lower version also registered.
The solution is to cache information about the old add-in version, and when comparing ids, use that information.
Added unit tests.

Fix add-in downgrade issue

---

Mono.Addins.Gui/Mono.Addins.Gui/AddinManagerDialog.cs
Mono.Addins.Gui/Mono.Addins.Gui/NewSiteDialog.cs
Mono.Addins.GuiGtk3/Mono.Addins.Gui/AddinManagerDialog.cs
Mono.Addins.GuiGtk3/Mono.Addins.Gui/NewSiteDialog.cs

Mono and .NET, before .NET 8, would resolve the
System.Environment.SpecialFolder.Personal enum value to the $HOME directory. In .NET 8 this is changing. The Personal folder will now refer to $XDG_DOCUMENTS_DIR if set or $HOME/Documents otherwise.
Replace all uses of Environment.SpecialFolder.Personal with Environment.SpecialFolder.UserProfile so the code behaves as it did before. UserProfile still maps to $HOME
dotnet/runtime#68610
Note: Not sure this is needed - only looks like SpecialFolder.Personal is only used in gtk# UI and mono is not being updated with this change.

Use Environment.SpecialFolder.UserProfile instead of Personal

---

Mono.Addins/Mono.Addins/ExtensionContextTransaction.cs
Test/FileContentExtension/FileContentExtension.addin.xml
Test/UnitTests/SimpleApp.addin.xml
Test/UnitTests/TestEvents.cs
Test/UnitTests/TestMultithreading.cs
Version.props

When removing many nodes in a transaction it may happen that a parent is removed before its children, since the list of nodes to remove is in a hashset, so there is no defined order. Added a null check to avoid a crash when that happens.

Fix NRE when unloading an add-in

---

Mono.Addins.Setup/Mono.Addins.Setup.csproj
Mono.Addins/Mono.Addins.Database/DatabaseConfiguration.cs
Mono.Addins/Mono.Addins/AddinEngine.cs
Mono.Addins/Mono.Addins/ExtensionContext.cs
Mono.Addins/Mono.Addins/ExtensionContextTransaction.cs
Mono.Addins/Mono.Addins/ExtensionNode.cs
Test/UnitTests/TestEvents.cs
Test/UnitTests/TestExtensions.cs
Version.props

Moved notification queue from ExtensionContext to to add-in engine. The problem was that when a node is removed, it is not bound to a context anymore, but it may still need to make use of the event queue.

Fixed several exceptions that happen when unloading nodes 

---

Mono.Addins/Mono.Addins/AddinEngine.cs
Mono.Addins/Mono.Addins/ExtensionContext.cs
Mono.Addins/Mono.Addins/ExtensionNode.cs
Test/UnitTests/TestEvents.cs
Version.props

Event handler invocations are done through a dispatch queue, to ensure that they are dispatched in the right order in multi-threading scenarios. The dispatch queue is also used when invoking a handler as a result of an event subscription. For example, when calling AddExtensionNodeHandler, the handler should be immediately invoked for all existing nodes in the provided extension path. However, if AddExtensionNodeHandler was invoked within an event handler, those invocations would be queued and not executed immediately as the caller would expect.
The solution is to do the handler invocation for existing nodes like it used to be, not through the queue. However, the actual event subscription still needs to be done through the queue, to avoid receiving unnecessary events. There is a more …

Fix nested event dispatch issue

---

.config/tsaoptions.json
azure-pipelines.yml

CodeQL is a static analysis tool that is able to scan source code to help detect security vulnerabilities. In mono/mono-addins, there already exists auto-injection of CodeQL's init and finalize tasks within the official default pipeline.
We enable CodeQL directly on the main pipeline as there are relatively few jobs, and because commits are relatively infrequent, there is no need for a separate pipeline to specify a cadence (periods between commits and therefore pipeline builds can be over a weeklong, so if there is no change, there is no need for a new codeql scan)
This PR does the following:
Enables CodeQL
Enable TSA with CodeQL

Enable CodeQL with TSA

---

Mono.Addins/Mono.Addins/AddinEngine.cs

Reset the initialized flag after disposing the registry, since the Dispose method checks that flag.
Fixes issue #205

Fix issue on shutdown
