mono/mono-addins

Mono.Addins/Mono.Addins.Database/AddinDatabase.cs, Mono.Addins/Mono.Addins.Database/DatabaseConfiguration.cs
Add support for application level addins-config.xml that can be used to disable add-ins that are shipped with the application.
=> App level addins config

Mono.Addins/Mono.Addins/AddinEngine.cs
Class is not static, only some of its API is.
=> [AddinEngine(docs)]: fix incorrect assertion

Mono.Addins/Mono.Addins.Database/AddinScanner.cs
"There are errors" isn't really a useful error. Make sure
each individual error has a source.
=> Report errors individually

Mono.Addins/Mono.Addins.Database/FileDatabase.cs
@mhutch asked for some explanation of the magic numbers in FileDatabase.cs
=> Add some explanation behind 9b673202536788b2a2b98e4882e1a30d196bc897

Mono.Addins.Gui/Mono.Addins.Gui/AddinManagerDialog.cs, Mono.Addins.GuiGtk3/Mono.Addins.Gui/AddinManagerDialog.cs
This regression was introduced with 47df1d4
=> Fixed search box in AddInManager not appearing

Mono.Addins/CustomConditionAttribute.cs, Mono.Addins/Mono.Addins.Database/AddinScanner.cs, Mono.Addins/Mono.Addins.csproj, Mono.Addins/Mono.Addins/CustomConditionAttribute.cs, Test/HelloWorldExtension/HelloWorldExtension.csproj, Test/HelloWorldExtension/HelloWriterWithCondition.cs, Test/UnitTests/ExtensionModel/GlobalInfoConditionAttribute.cs, Test/UnitTests/SimpleApp.addin.xml, Test/UnitTests/TestConditions.cs, Test/UnitTests/TestEvents.cs, Test/UnitTests/TestVerifyAddinDescription.cs, Test/UnitTests/UnitTests.csproj, Test/UnitTests/packages.config
=> Add support for condition attributes

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj
Fixes building in-repo and in MD repo.
=> [Build] Use nugets from the solution dir.

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector/Reflector.cs, Mono.Addins/Mono.Addins.Database/AddinDatabase.cs, Mono.Addins/Mono.Addins.Database/AddinFileSystemExtension.cs, Mono.Addins/Mono.Addins.Database/AddinScanner.cs
Fixes cecil-swap branch to work properly
=> Reflector fixes

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector/Reflector.cs
new cache - init->dispose millis
CECILREFLECTOR: 46791/47087
CECILREFLECTOR TIME: 1318ms
old cache - init->dispose millis
CECILREFLECTOR: 46680/47087
CECILREFLECTOR TIME: 3120ms
=> [Cecil] Optimize reflector loading by improving cache hit/misses ratio.

Mono.Addins.Gui/Mono.Addins.Gui/AddinInfoView.cs, Mono.Addins.Gui/Mono.Addins.Gui/AddinTreeWidget.cs, Mono.Addins.Gui/Mono.Addins.Gui/ProgressDialog.cs
Ambiguous call between Action and EventHandler with new Gtk#.
=> [Gtk#] Switch to explicit delegate handler.

Mono.Addins.Setup/Mono.Addins.Setup/SetupService.cs, Mono.Addins.Setup/Mono.Addins.Setup/SetupTool.cs
We support searching for pdb files as well as mdb files.
=> Add the ability to auto-import debug symbols

Mono.Addins/Mono.Addins/AddinEngine.cs, Mono.Addins/Mono.Addins/AddinManager.cs, Mono.Addins/Mono.Addins/RuntimeAddin.cs
This is fired when the addin assemblies are loaded.
=> Add AddinAssembliesLoaded event

Mono.Addins.CecilReflector/Mono.Addins.CecilReflector.csproj
MonoDevelop has switched to Cecil 0.10.1.
=> Bump Cecil to 0.10.1.

Mono.Addins.Gui/Mono.Addins.Gui/AddinManagerDialog.cs
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/750349
- changed focus chain for `Updates` and `Gallery` tabs
=> [750349] fixed focus chain (extensions window)

Mono.Addins/Mono.Addins.Database/AddinScanner.cs, Mono.Addins/Mono.Addins.Description/ExtensionNodeDescription.cs, Test/UnitTests/TestAddinDescription.cs
=> Fix serialization of addin localizer

Mono.Addins.Setup/Mono.Addins.Setup/SetupTool.cs
Fixes  https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1156791
Tasks Done:
This PR includes changes to enable and disable addins before starting VSFMac IDE.
=> Enable and Disable Addins

Mono.Addins/Mono.Addins.Database/AddinFileSystemExtension.cs, Test/UnitTests/TestBase.cs, Test/UnitTests/TestScanDataFileGeneration.cs
Fixed several issues that caused unit tests to always fail when running from
inside VS Mac.
=> Fix unit tests

Mono.Addins/Mono.Addins.Database/AddinFolderVisitor.cs
Revert some conditions in AddinFolderVisitor so that the fastest
condition is evaluated first
=> Minor perf optimization

Mono.Addins/Mono.Addins/AddinEngine.cs, Mono.Addins/Mono.Addins/ExtensionContext.cs, Mono.Addins/Mono.Addins/RuntimeAddin.cs
Delay the lookup of condition and localizer types until the objects
are actually going to be used. Also avoid loading types for
type based extension points. Types were loaded to map them to
corresponding extension paths, but the mapping can be done
using the type name instead of the actual type instance.
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1528125
Fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1528141
FIxes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1528129
=> Delay add-in assembly load by lazy creating objects

Mono.Addins/Mono.Addins.csproj
Would be nice to have this, otherwise we can't debug into Mono.Addins:
=> Embed Pdb and add SourceLink

azure-pipelines.yml
Removed Cadence configuration value, so that it uses the default value. Added comment.
=> Fix CodeQL configuration

.config/tsaoptions.json, azure-pipelines.yml, compliance.yaml
Separate build pipeline to run on a schedule.
=> Add SBOM, CredScan, PoliCheck and CodeQL
